# Generated by Django 2.1.1 on 2018-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='Github link.', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='Project link.', max_length=50),
        ),
    ]
