# Generated by Django 2.1.1 on 2018-09-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180918_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('category',)},
        ),
    ]
